name: Deploys QA Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploys: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy Namespaces Manifest
        run: kubectl apply -f Environments/QA/namespace.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Initializes Terraform QA Enviroment
        run: terraform init
        working-directory: Environments/QA

      - name: Validates Terraform QA Enviroment
        run: terraform validate
        working-directory: Environments/QA
      
      - name: Plans Terraform QA Enviroment
        run: terraform plan 
        working-directory: Environments/QA

      - name: Applys Terraform QA Enviroment
        run: terraform apply --auto-approve
        working-directory: Environments/QA



