name: Deploys QA Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploys: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Initializes Terraform QA Enviroment
        run: terraform init
        working-directory: eks/Environments/QA


      - name: Validates Terraform QA Enviroment
        run: terraform validate
        working-directory: eks/Environments/QA
      
      - name: Plans Terraform QA Enviroment
        run: terraform plan 
        working-directory: eks/Environments/QA

      - name: Applys Terraform QA Enviroment
        run: terraform apply --auto-approve
        working-directory: eks/Environments/QA



