name: Deploys QA Infrastructure

#on:
#  push:
#    branches:
#      - main

jobs:
  deploys: 
    runs-on: ubuntu-latest
    defaults:
      runs:
        working-directory: eks/Enviroments/UAT

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Initializes Terraform QA Enviroment
        runs: terraform init

      - name: Validates Terraform QA Enviroment
        runs: terraform validate
      
      - name: Plans Terraform QA Enviroment
        runs: terraform plan 

      - name: Applys Terraform QA Enviroment
        runs: terraform apply --auto-approve



